#
# MIT License
#
# Copyright (c) 2025 Elektroline
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: "Rust pycobertura"
description: "Generate pycobertura reports for Rust projects"
inputs:
  project_name:
    description: "Name of the project used for filenames / in text"
    required: true
  commit_name:
    description: "Commit hash used for filenames"
    default: ${{github.event.pull_request.head.sha || github.sha}}
  cargo_test_arguments:
    description: "Specify custom arguments for cargo test"
    default: "--all-features"
  fail_if_worse:
    description: "Whether to fail pycobertura says so"
    default: "false"
  rust_toolchain:
    description: "Which toolchain to choose (stable/nightly)"
    default: "stable"
  cache_key:
    description: "An additional key for the coverage cache"
    required: false
    default: ${{ github.workflow }}-${{ github.job }}

runs:
  using: "composite"
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: x86_64-unknown-linux-gnu
        toolchain: ${{inputs.rust_toolchain}}
        override: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Install pycobertura
      uses: insightsengineering/pip-action@v2
      with:
        packages: pycobertura==3.3.2

    - name: Checkout PR HEAD
      uses: actions/checkout@v4
      with:
        path: pr-head

    - name: Checkout base-ref
      uses: actions/checkout@v4
      with:
        path: base-ref
        ref: ${{github.event.pull_request.base.ref || github.event.before}}

    - name: Figure out commit hashes for cache
      id: commit-hashes
      run: |
        for CODE_REF in base-ref pr-head; do
          echo "${CODE_REF}=$(git -C "$CODE_REF" rev-parse HEAD)" >> "$GITHUB_OUTPUT"
        done
      shell: bash

    - name: Setup code coverage cache for PR HEAD
      uses: actions/cache@v4
      with:
        key: rust-pycobertura-${{inputs.cache_key}}-${{steps.commit-hashes.outputs.pr-head}}
        path: pr-head/*-cobertura.xml

    - name: Setup code coverage cache for base-ref
      uses: actions/cache@v4
      with:
        key: rust-pycobertura-${{inputs.cache_key}}-${{steps.commit-hashes.outputs.base-ref}}
        path: base-ref/*-cobertura.xml

    - name: Generate code coverage
      run: |
        for CODE_DIR in pr-head base-ref; do
          (
            cd "${{github.workspace}}/$CODE_DIR"
            COVERAGE_FILENAME='${{inputs.project_name}}-cobertura.xml'
            if [[ -f "$COVERAGE_FILENAME" ]]; then
              echo Coverage for "$CODE_DIR" exists, skipping.
              exit 0
            fi
            cargo llvm-cov --cobertura --output-path "$COVERAGE_FILENAME" ${{inputs.cargo_test_arguments}}
          )
        done
      shell: bash

    - name: Set pycobertura exit codes
      run: |
        echo "PYCOBERTURA_SUCCESS=0" >> "$GITHUB_ENV"
        echo "PYCOBERTURA_EXCEPTION=1" >> "$GITHUB_ENV"
        echo "PYCOBERTURA_COVERAGE_WORSENED=2" >> "$GITHUB_ENV"
        echo "PYCOBERTURA_NOT_ALL_CHANGES_COVERED=3" >> "$GITHUB_ENV"
      shell: bash

    - name: Generate pycobertura text and HTML report
      run: |
        PYCOBERTURA_STATUS=0
        set -x
        for FORMAT in markdown html; do
          pycobertura \
            show \
            --format "$FORMAT" \
            --source '${{github.workspace}}/pr-head' \
            --output "${{github.workspace}}/${{inputs.project_name}}-pycobertura-show-${{inputs.commit_name}}.$FORMAT" \
            '${{github.workspace}}/pr-head/${{inputs.project_name}}-cobertura.xml' || PYCOBERTURA_STATUS=$?

          pycobertura \
            diff \
            --format "$FORMAT" \
            --no-color \
            --source1 '${{github.workspace}}/base-ref' \
            --source2 '${{github.workspace}}/pr-head' \
            --output "${{github.workspace}}/${{inputs.project_name}}-pycobertura-diff-${{inputs.commit_name}}.$FORMAT" \
            '${{github.workspace}}/base-ref/${{inputs.project_name}}-cobertura.xml' \
            '${{github.workspace}}/pr-head/${{inputs.project_name}}-cobertura.xml' || PYCOBERTURA_STATUS=$?
        done

        if [[ "$PYCOBERTURA_STATUS" = ${{env.PYCOBERTURA_EXCEPTION}} ]]; then
          false
        fi

        cat '${{github.workspace}}/${{inputs.project_name}}-pycobertura-show-${{inputs.commit_name}}.markdown'
        echo
        cat '${{github.workspace}}/${{inputs.project_name}}-pycobertura-diff-${{inputs.commit_name}}.markdown'

        echo "PYCOBERTURA_STATUS=$PYCOBERTURA_STATUS" >> "$GITHUB_ENV"
      shell: bash

    - name: Upload HTML reports
      id: html-reports
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.project_name}}-cov-html-${{inputs.commit_name}}
        path: ${{github.workspace}}/${{inputs.project_name}}-pycobertura-*-${{inputs.commit_name}}.html

    - name: Generate sticky comment contents
      run: |
        # shellcheck disable=SC2016
        {
          echo '## Code coverage report for ${{inputs.commit_name}}'

          echo '#### Coverage difference'
          case ${{env.PYCOBERTURA_STATUS}} in
            ${{env.PYCOBERTURA_SUCCESS}})
              echo ✅ All new changes were covered.
              ;;
            ${{env.PYCOBERTURA_COVERAGE_WORSENED}})
              echo ❌ Code coverage worsened.
              ;;
            ${{env.PYCOBERTURA_NOT_ALL_CHANGES_COVERED}})
              echo ⚠️ There are new lines with missing coverage.
              ;;
          esac

          cat '${{github.workspace}}/${{inputs.project_name}}-pycobertura-diff-${{inputs.commit_name}}.markdown'

          echo
          echo

          echo '#### Overall coverage'
          echo '<details>'
          echo '<summary>Click to expand</summary>'
          echo '<span>'
          echo
          cat '${{github.workspace}}/${{inputs.project_name}}-pycobertura-show-${{inputs.commit_name}}.markdown'
          echo
          echo '</span>'
          echo '</details>'

          echo
          echo '#### HTML reports'
          echo 'You can use _GitHub CLI_ to download HTML coverage reports and open them automatically using this command:'
          echo '```bash'
          echo '(cd "$(mktemp -d)" && gh run -R ${{github.repository}} download -n ${{inputs.project_name}}-cov-html-${{inputs.commit_name}} && ls -1 | xargs -n1 xdg-open)'
          echo '```'
          echo
          echo 'You can download the HTML reports manually [here](${{steps.html-reports.outputs.artifact-url}})'.
          echo
        } > sticky-comment.md
      shell: bash

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: sticky-comment.md
    - name: Fail if coverage is worse
      if: inputs.fail_if_worse != 'false'
      run: |
        if [[ ${{env.PYCOBERTURA_STATUS}} != ${{env.PYCOBERTURA_SUCCESS}} ]]; then
          false
        fi
      shell: bash

    - name: Fail on pycobertura exception
      if: inputs.fail_if_worse == 'false'
      run: |
        if [[ ${{env.PYCOBERTURA_STATUS}} = ${{env.PYCOBERTURA_EXCEPTION}} ]]; then
          false
        fi
      shell: bash

branding:
  icon: "archive"
  color: "gray-dark"
